Repository jitacm/30-daysJava-Student_Management, pull requests merged in 2025-08, with the labels that each got.

#4 Added GUI
  Student Managment Application/out/gui/StudentManagementGUI$1.class
  Student Managment Application/out/gui/StudentManagementGUI$2.class
  Student Managment Application/out/gui/StudentManagementGUI$RoundedButton$1.class
  Student Managment Application/out/gui/StudentManagementGUI$RoundedButton.class
  Student Managment Application/out/gui/StudentManagementGUI.class
  Student Managment Application/out/main/Client.class
  Student Managment Application/src/gui/StudentManagementGUI.java
  Student Managment Application/src/main/Client.class
  Student Managment Application/src/main/Client.java
Labels: 30daysdevchallenge, jitacm, uiux, level-4

#6 Updated Readme File for System
  README.md
Labels: documentation, 30daysdevchallenge, jitacm, level-2

#8 Added Modern Login Dialog and Enhanced Universal Search Bar
  Student Managment Application/out/gui/LoginDialog.class
  Student Managment Application/out/gui/StudentManagementGUI$1.class
  Student Managment Application/out/gui/StudentManagementGUI$2.class
  Student Managment Application/out/gui/StudentManagementGUI$3.class
  Student Managment Application/out/gui/StudentManagementGUI$4.class
  Student Managment Application/out/gui/StudentManagementGUI$RoundedButton$1.class
  Student Managment Application/out/gui/StudentManagementGUI$RoundedButton.class
  Student Managment Application/out/gui/StudentManagementGUI.class
  Student Managment Application/out/main/Client.class
  Student Managment Application/src/gui/LoginDialog.java
  Student Managment Application/src/gui/StudentManagementGUI.java
  Student Managment Application/src/main/Client.java
Labels: 30daysdevchallenge, jitacm, feature, level-3, uiux

#10 Fix Login Dialog Keyboard Navigation and Resizable Window
  Student Managment Application/out/gui/LoginDialog.class
  Student Managment Application/out/gui/StudentManagementGUI$4.class
  Student Managment Application/out/gui/StudentManagementGUI$5.class
  Student Managment Application/out/gui/StudentManagementGUI$RoundedButton$1.class
  Student Managment Application/out/gui/StudentManagementGUI$RoundedButton.class
  Student Managment Application/out/gui/StudentManagementGUI.class
  Student Managment Application/src/gui/LoginDialog.java
  Student Managment Application/src/gui/StudentManagementGUI.java
Labels: bug, 30daysdevchallenge, jitacm, level-3

#12 Comprehensive README.md enhancement with detailed documentation
  README.md
  Student Managment Application/src/dao/StudentDao.class
  Student Managment Application/src/dao/StudentDaoInterface.class
  Student Managment Application/src/gui/ExportUtil.java
  Student Managment Application/src/gui/StudentManagementGUI.java
  Student Managment Application/src/model/Student.class
Labels: documentation, 30daysdevchallenge, jitacm, level-2

#16 Enhanced Analytics & Reporting Implementation Done #15
  Student Managment Application/src/dao/StudentDao.java
  Student Managment Application/src/gui/DashboardPanel.java
  Student Managment Application/src/gui/ExportUtil.java
  Student Managment Application/src/gui/StudentManagementGUI.java
Labels: 30daysdevchallenge, jitacm, uiux
